### ISSUE TITLE
Creating a schema includes the provided schema name as a prefix.

### ISSUE THREAD

**Issue by ahedengren** [mpcarter/dbt-vertica#19]
When using the config to set the schema, the database name gets set as a prefix.

Unsure if this is intended or not. From the below code, I'd expect the a new schema named `staging` not `vmart_staging`.

profiles.yml
```
vmart_examples:
  target: dev
  outputs:
    dev:
      type: vertica
      host: localhost
      port: 5433
      username: dbadmin
      password: ''
      database: vmart
      schema: vmart
      threads: 2
```

stg_online_page_dimension.sql
```
{{
  config(
    schema='staging',
    materialized='table',
    tags=['staging']
  )
}}

with source as
(
    select 
      online_page_key as online_page_id,
      start_date as start_at,
      end_date as end_date,
      page_number as page_number,
      page_description as page_description,
      page_type as page_type
    from {{ source('online_sales','online_page_dimension') }}
)
select * 
from source
```
